name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

   # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

 
